name: Upload To Cos After Release

on:
  release:
    types: [published]
    branches: [ "TOHE" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -c "import sys; print(sys.version)"
    - name: Put Request To Cos
      env:
        PUT_URL: ${{ secrets.PUT_URL }}
        COS_HOST: ${{ secrets.COS_HOST }}
      run: |
        import os
        import requests
        
        file = './Release/TOHE.dll'
        size = os.stat(file).st_size
        with open (file, 'rb') as file_object:
          contents = file_object.read()
        
        url = os.environ.get('PUT_URL')
        headers = {'Content-Type': 'application/x-msdownload', 'Host': os.environ.get('COS_HOST') }
        
        req = requests.put(url, data = contents, headers = headers)
        
        print('File Size: ' + str(size))
        print('Status Code: ' + str(req.status_code))
        
        if req.status_code == 200: print('√ Successfully uploaded to Tencent Cloud Cos!')
        else: print('× Upload to Tencent Cloud Cos failed:\n\n' + req.text)
        
      shell: python
